spring:
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bestuser
    hikari:
      schema: eshop
  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: eshop
  main:
    allow-circular-references: true